FROM node:14

RUN mkdir -p /usr/src/nuxt-frontend
WORKDIR /usr/src/nuxt-frontend
COPY . .

ENV NODE_ENV=production
ENV NUXT_PORT=3000
ENV NUXT_HOST=0.0.0.0
ENV NUXT_ENV_API_URL=https://questionnaire-be-api.azurewebsites.net

RUN npm rebuild node-sass && npm install && npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
