FROM node:14

RUN mkdir -p /usr/src/nuxt-frontend
WORKDIR /usr/src/nuxt-frontend
COPY . .

ENV NODE_ENV=production
ENV NUXT_PORT=3000
ENV NUXT_HOST=0.0.0.0
# ENV NUXT_ENV_API_URL=https://bg-api.f048f36cd9de4dccae74.southeastasia.aksapp.io/API/v2

RUN npm install --production && npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
